builds:
  - main: main.go
    binary: gitstats
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le

changelog:
  sort: asc
  filters:
    exclude:
      - balls
      - docs
      - Merge pull request
      - Merge branch

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
      - LICENSE
      - README.md
