builds:
  - main: .
    binary: gitstats
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - balls
      - docs
      - Merge pull request
      - Merge branch

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
      - LICENSE
      - README.md
